services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=shk,g-hkot0Ut
    volumes:
      - mongo-data:/data/db
    networks:
      - go-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=shk,g-hkot0Ut
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=shk,g-hkot0Ut
    depends_on:
      - mongodb
    networks:
      - go-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - go-network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - 8001:8001
    environment:
      - REDIS_OSS_CLUSTER=false
    depends_on:
      - redis
    networks:
      - go-network
  
  postgres:
    image: postgres:14.9
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=shk,g-hkot0Ut
      - POSTGRES_DB=tlkr
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - go-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=shk,g-hkot0Ut
    depends_on:
      - postgres
    networks:
      - go-network

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
  postgres-data:
    driver: local

networks:
  go-network:
    external: false
    name: go-network
